"""
DESCRIPTION:
This script analyzes historical sales data to answer two critical
resource management questions when an employee submits their resignation:

    1. Replacement Decision: Is it financially profitable to hire a replacement?
    2. Overlap Effect: What is the effect of having 8 staff (including the departing employee and 
    onboarding the replacement) on the gross margin for notice period month.

Both evaluations weigh the 45% gross margin generated by incremental sales 
against a baseline monthly salary cost of 3 units per employee.
--------------------------------------------------------------------------------
ENVIRONMENT & PREREQUISITES:
--------------------------------------------------------------------------------
Ensure you are using a virtual environment with 'pandas' installed:
Navigate to current file directory and run the following commands in the terminal:
    $ python3 -m venv venv
    $ source venv/bin/activate
    $ pip install -r requirements.txt

Note: Built-in libraries 'os' is part of the Python standard library.
--------------------------------------------------------------------------------
HOW TO RUN:
--------------------------------------------------------------------------------
Execute the script directly from your terminal. It will interactively guide you
through the required inputs:

    $ python <script_name>.py

Interactive Prompts:
    1. Dataset Path: Enter the relative or absolute path to your file.
       (e.g., ./RevI-Test.csv)
    2. Employee ID: Enter the ID of the leaving staff member. The script 
       automatically normalizes both numbers or formatted strings.
       (e.g., entering '12' or 'sp12' will both map correctly to 'sp12')
"""

import os
import pandas as pd


def estimate_sales(s_df, counts, target_count): 
    """
    Get or estimate average sales for a given target staff_count.
    Uses binary search to find the surrounding counts when exact match not found. 
    """
    # Exact match
    if target_count in counts:
        return float(s_df[s_df["staff_count"] == target_count]["Sales"].iloc[0])

    # Out of range — clamp to edges
    if target_count < counts[0]:
        return float(s_df[s_df["staff_count"] == counts[0]]["Sales"].iloc[0])
    if target_count > counts[-1]:
        return float(s_df[s_df["staff_count"] == counts[-1]]["Sales"].iloc[0])

    # Binary search for surrounding counts 
    l = 0
    r = len(counts) - 1
    m = len(counts) // 2

    while l != r - 1:
        if counts[m] == target_count:
            l = m
            r = m
        elif target_count > counts[m]:
            l = m
            m = (l + r) // 2
        else:
            r = m
            m = (l + r) // 2

    sales_l = float(s_df[s_df["staff_count"] == counts[l]]["Sales"].iloc[0])
    sales_r = float(s_df[s_df["staff_count"] == counts[r]]["Sales"].iloc[0])

    # Calculated interpolated value using nearest neighbors counts avg sales
    interpolated = sales_l + (sales_r - sales_l) * (target_count - counts[l]) / (counts[r] - counts[l])

    return interpolated



def load_and_prepare(url, emp_id):
    df = pd.read_csv(url)
    df.columns = df.columns.str.strip()

    x = "sale " + emp_id
    notice_month = int(df[df[x] > 0]["Month"].values.max())
    df = df[df["Month"] <= notice_month].copy()

    
    spcols = df.columns[2:]
    df["staff_count"] = (df[spcols] != 0).sum(axis=1)


    sc = int(df[df["Month"] == notice_month]["staff_count"])

    s_df = (
        df.groupby("staff_count")["Sales"]
        .mean()
        .reset_index()
        .sort_values("staff_count")
    )

    counts = s_df["staff_count"].tolist()

    return df, sc, s_df, counts


def get_recommendation(url, emp_id):
    """
    QUESTION 1: After emp_id leaves, should you hire a replacement?

    After resignation you have (sc - 1) staff.
    Hire decision = does adding 1 person back to (sc-1) improve 6-month gross margin?

    Scenario A (Hire)     : sc   staff for all 6 months
    Scenario B (Don't)    : sc-1 staff for all 6 months

    Gross_margin_Hire    = 6 * [0.45 * sales_sc     - sc     * 3]
    Gross_margin_No_Hire = 6 * [0.45 * sales_sc_1   - (sc-1) * 3]

    Delta_gross_margin = Gross_margin_Hire - Gross_margin_No_Hire
          = 6 * [0.45 * (sales_sc - sales_sc_1) - 3]

    if Delta_gross_margin > 0: the new hire is profitable(does enough sales to offset the salary cost)
    else: the new hire is not profitable

    """
    df, sc, s_df, counts = load_and_prepare(url, emp_id)
    monthly_salary = 3

    sales_sc   = estimate_sales(s_df, counts, sc)
    sales_sc_1 = estimate_sales(s_df, counts, sc - 1)

    incremental_sales = sales_sc - sales_sc_1  # extra sales from having sc vs sc-1

    # Gross margin gained per month by hiring
    delta_per_month = 0.45 * incremental_sales - monthly_salary

    # Over 6 months
    delta_6_months = 6 * delta_per_month

    print(f"--- Replacement Decision for {emp_id} ---")
    print(f"Staff headcount before resignation : {sc}")
    print(f"Headcount after {emp_id} leaves           : {sc - 1}")
    print(f"Avg Sales at {sc - 1} staff               : {round(sales_sc_1, 2)}")
    print(f"Avg Sales at {sc}     staff               : {round(sales_sc, 2)}")
    print(f"Incremental Sales from 1 extra person     : {round(incremental_sales, 2)}")
    print(f"Delta Gross Margin per month              : {round(delta_per_month, 3)}")
    print(f"Delta Gross Margin over 6 months          : {round(delta_6_months, 3)}")
    print()

    if delta_6_months > 0:
        action = 1 # Hire
        print(f"👉 RECOMMENDATION: Hire a replacement for {emp_id}")
        print(f"   Adding 1 person back to {sc - 1} staff generates {round(delta_6_months, 3)} "
              f"extra margin units over 6 months.\n")
    else:
        action = 0 # Do not Hire
        print(f"👉 RECOMMENDATION: Do NOT hire a replacement for {emp_id}")
        print(f"   Running at {sc - 1} staff is more profitable. "
              f"The extra salary outweighs the incremental sales.\n")

    return action


def evaluate_notice_month_gross_margin_effect(url, emp_id):
    """
    QUESTION 2: Is the overlap model (hiring during notice period) worth it?

    Only meaningful if get_recommendation() says hire.

    During notice month, sp12 is still working. Two choices:
        Overlap     : sc-1 remaining + sp12 + new hire = sc+1 staff
        No-overlap  : sc-1 remaining + sp12            = sc   staff

    Months 2-6 are IDENTICAL in both models (sc staff either way) → they cancel out.
    Only Month 1 differs.

    GM_overlap    = 0.45 * sales_sc_plus_1 - (sc+1) * 3
    GM_no_overlap = 0.45 * sales_sc        - sc     * 3

    Delta_overlap = GM_overlap - GM_no_overlap
                  = 0.45 * (sales_sc_plus_1 - sales_sc) - 3
    """
    df, sc, s_df, counts = load_and_prepare(url, emp_id)
    monthly_salary = 3

    sales_sc        = estimate_sales(s_df, counts, sc)
    sales_sc_plus_1 = estimate_sales(s_df, counts, sc + 1)

    incremental_sales_overlap = sales_sc_plus_1 - sales_sc  # extra from sc+1 vs sc

    # Month 1 only — months 2-6 cancel out
    delta_overlap = 0.45 * incremental_sales_overlap - monthly_salary

    print(f"--- Notice Month Gross Margin Evaluation ---")
    print(f"Steady state headcount (sc)               : {sc}")
    print(f"Staff during notice — Overlap model       : {sc + 1}")
    print(f"Staff during notice — No-overlap model    : {sc}")
    print(f"Avg Sales at sc   ({sc} staff)            : {round(sales_sc, 2)}")
    print(f"Avg Sales at sc+1 ({sc + 1} staff)        : {round(sales_sc_plus_1, 2)}")
    print(f"Incremental Sales during overlap month    : {round(incremental_sales_overlap, 2)}")
    print(f"Delta Gross Margin for notice month only  : {round(delta_overlap, 3)}")
    print(f"  → Months 2-6 are identical in both models and cancel out")
    print()

    if delta_overlap > 0:
        print("👉 OVERLAP VERDICT:")
        print(f"   Having {sc + 1}th staff during the notice period month adds {round(delta_overlap, 3)} "
              f"margin units vs waiting.\n")
    else:
        print("👉 OVERLAP VERDICT: ⚠️ Warning")
        print(f"   Having {sc + 1}th staff during the notice period month costs {round(abs(delta_overlap), 3)} "
              f"margin units. If possible start the new hire AFTER {emp_id} leaves instead.\n")

    return delta_overlap

def load_and_prepare(file_path, emp_id):
    # Handle relative or absolute file paths safely
    absolute_path = os.path.abspath(file_path)
    if not os.path.exists(absolute_path):
        raise FileNotFoundError(f"The file data source was not found at: {absolute_path}")

    df = pd.read_csv(absolute_path)
    df.columns = df.columns.str.strip()

    x = "sale " + emp_id
    if x not in df.columns:
        raise KeyError(f"Column '{x}' not found in the dataset. Check your employee ID input.")

    notice_month = int(df[df[x] > 0]["Month"].values.max())
    df = df[df["Month"] <= notice_month].copy()
    
    spcols = df.columns[2:]
    df["staff_count"] = (df[spcols] != 0).sum(axis=1)

    sc = int(df.iloc[-1]["staff_count"])

    s_df = (
        df.groupby("staff_count")["Sales"]
        .mean()
        .reset_index()
        .sort_values("staff_count")
    )
    counts = s_df["staff_count"].tolist()

    return df, sc, s_df, counts

if __name__ == "__main__":
    print("====================================================")
    print("      Hiring & Overlap Model Evaluation Tool        ")
    print("====================================================\n")
    
    # 1. Interactively grab file path from user
    raw_file = input("Enter the dataset path (e.g., ./RevI-Test.csv): ").strip()
    
    # 2. Interactively grab employee ID from user
    raw_emp_id = input("Enter the employee ID (e.g., 12 or sp12): ").strip()
    print("\nProcessing analysis...\n")

    formatted_emp_id = raw_emp_id if raw_emp_id.startswith("sp") else f"sp{raw_emp_id}"

    try:
        # Run calculations
        get_recommendation(raw_file, formatted_emp_id)
        evaluate_notice_month_gross_margin_effect(raw_file, formatted_emp_id)
    except Exception as e:
        print(f"❌ Error: {e}")
